import AppKit

/// Loads the Fish kingdom's bundled swim-frame PNGs (generated by `scripts/build-fish-frames.py`
/// under `Resources/fish/<slug>/<stage>/frame-<i>.png`). Fish ship local sprites, so this is the
/// offline analog of the Pokémon `SpriteStore` remote-GIF path — the frames feed straight into
/// `SpriteView`'s existing frame-cycling animator.
@MainActor
enum FishSprites {
    /// Frames per swim cycle — must match `scripts/build-fish-frames.py` TAIL_ANGLES count.
    static let frameCount = 4
    /// Per-frame duration for the tail-wag cycle (seconds). ~8 fps reads as a relaxed swim and
    /// is battery-cheap for the always-on floating pet.
    static let frameDelay: TimeInterval = 0.13

    private static var cache: [String: [NSImage]] = [:]

    /// Ordered swim frames for a fish stage id. Shiny falls back to the normal morph if no shiny
    /// frames are bundled. Empty array = nothing bundled (caller shows a static/egg fallback).
    static func frames(stageID: Int, shiny: Bool) -> [NSImage] {
        guard let sp = FishCatalog.shared.speciesInfo(forStageID: stageID),
              let stage = sp.stageByID[stageID] else { return [] }
        if shiny {
            let shinyFrames = load(slug: sp.dirSlug, stage: stage.spriteFile + "-shiny")
            if !shinyFrames.isEmpty { return shinyFrames }
        }
        return load(slug: sp.dirSlug, stage: stage.spriteFile)
    }

    /// First swim frame — used as the synchronous static seed (avoids a render flash).
    static func firstFrame(stageID: Int, shiny: Bool) -> NSImage? {
        frames(stageID: stageID, shiny: shiny).first
    }

    private static func load(slug: String, stage: String) -> [NSImage] {
        let key = "\(slug)/\(stage)"
        if let cached = cache[key] { return cached }
        var imgs: [NSImage] = []
        for i in 0..<frameCount {
            guard let url = Bundle.module.url(forResource: "frame-\(i)", withExtension: "png",
                                              subdirectory: "fish/\(slug)/\(stage)"),
                  let img = NSImage(contentsOf: url) else { break }
            imgs.append(img)
        }
        cache[key] = imgs
        return imgs
    }
}
